insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Awalé', 'Awale.png', '8+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Puluc', 'Puluc.png', '8+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Jeux de go', 'Go.png', '8+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Hanabi', 'Hanabi.png', '8+', 3);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Citadelles', 'Citadelles.png', '8+', 3);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Monopoly Fortnite', 'Monopoly.png', '6+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Echec', 'Echec.png', '8+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Qui est-ce ?', 'QuiEstCe.png', '6+', 1);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Loups garous', 'LoupsGarous.png', '8+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Jungle speed', 'JungleSpeed.png', '6+', 1);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Yams', 'Yams.png', '8+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Petits chevaux', 'PetitsChevaux.png', '6+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Times up', 'TimesUp.png', '12+', 1);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Dominos', 'Dominos.png', '6+', 1);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('La bonne paye', 'LaBonnePaye.png', '8+', 3);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Blokus', 'Blokus.png', '8+', 1);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Docteur maboul', 'DocteurMaboul.png', '6+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Jenga', 'Jenga.png', '6+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Jeux de dame', 'JeuxDeDame.png', '8+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Croc dog', 'CrocDog.png', '4+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Jimmy la souris', 'JimmyLaSouris.png', '4+', 1);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Kyyänimo', 'Kyyanimo.png', '4+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('La vallée des vikings', 'ValleeVikings.png', '6+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Labyrinthe', 'Labyrinthe.png', '3+', 3);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Cluedo', 'Cluedo.png', '8+', 3);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Perudo', 'Perudo.png', '8+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Wazabi', 'Wazabi.png', '8+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Shogi', 'Shogi.png', '8+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Backgammon', 'Backgammon.png', '8+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Mutants', 'Mutants.png', '8+', 1);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Where is Mr Wolf', 'WhereIsMrWolf.png', '8+', 1);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Uno', 'Uno.png', '6+', 1);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Coatl', 'Coatl.png', '10+', 1);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('6 qui prend', '6QuiPrend.png', '6+', 2);
insert into jeu (nom, lienimage, trancheage, nbpoint) values ('Au creux de ta main', 'AuCreuxDeTaMain.png', '10+', 2);